<form class="form-horizontal" role="form" action="/application/index/signup" method="post">
	<div class="form-group">
		<div class="col-sm-6 padfix-left">
			<input type="fname" class="form-control" id="fname" name="fname" placeholder="First name">
		</div>
		<div class="col-sm-6 padfix-right">
			<input type="lname" class="form-control" id="lname" name="lname" placeholder="Last name">
		</div>
		
	</div>
	<div class="form-group">
		<input type="email" class="form-control" id="email" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<input type="password" class="form-control" id="password" name="password" placeholder="Password">
	</div>
	<div class="form-group">
		<div class="col-sm-5 padfix-left">
			<button type="submit" class="btn btn-primary btn-lg btn-block"><?php echo $this->translate('Sign up') ?></button>
		</div>
	</div>
</form>