<form class="form-horizontal" role="form" action="/application/index/signin" method="post">
	<div class="form-group">
		<input type="email" class="form-control" id="email" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<input type="password" class="form-control" id="password" name="password" placeholder="Password">
	</div>
	<div class="form-group">
		<div class="col-sm-5 padfix-left">
			<button type="submit" class="btn btn-primary btn-lg btn-block"><?php echo $this->translate('Sign in') ?></button>
		</div>
	</div>
</form>